#Customised from https://github.com/antoiner77/caddy-ansible
- include_vars: vault_caddyfile.yml
- name: Create Caddy group
  group: name={{ caddy_user }} state=present
  become: true

- name: Create Caddy user
  user: name={{ caddy_user }} system=yes createhome=yes home={{ caddy_home }} group={{ caddy_user }}
  become: true
 
- name: Get all Caddy releases
  get_url: url=https://api.github.com/repos/mholt/caddy/git/refs/tags dest={{ caddy_home }}/releases.txt force=yes
  when: caddy_update
  register: caddy_releases_cache 
  become: true

- name: Set Caddy features
  copy: content="{{ caddy_features }}" dest={{ caddy_home }}/features.txt
  when: caddy_update
  register: caddy_features_cache
  become: true

- name: Download Caddy
  get_url: url=https://caddyserver.com/download/build?os=linux&arch=amd64&features={{ caddy_features }} dest={{ caddy_home }}/caddy.tar.gz force=yes
  when: caddy_releases_cache.changed or caddy_features_cache.changed
  register: caddy_binary_cache
  become: true

- name: Download Caddy
  get_url: url=https://caddyserver.com/download/build?os=linux&arch=amd64&features={{ caddy_features }} dest={{ caddy_home }}/caddy.tar.gz
  become: true

- name: Extract Caddy
  unarchive: src={{ caddy_home }}/caddy.tar.gz dest={{ caddy_home }} copy=no owner={{ caddy_user }}
  when: caddy_binary_cache.changed
  become: true

- name: Extract Caddy
  unarchive: src={{ caddy_home }}/caddy.tar.gz dest={{ caddy_home }} creates={{ caddy_home }}/caddy copy=no owner={{ caddy_user }}
  become: true

- name: Copy Caddy Binary
  copy: src={{ caddy_home }}/caddy dest=/usr/local/bin/ mode=0755 remote_src=True
  become: true
  notify: Restart Caddy

- name: Create directories
  file: path={{ item }} state=directory owner={{ caddy_user }} mode=0700
  become: true
  with_items:
    - /etc/caddy
    - /etc/ssl/caddy
    - /var/log/caddy

- name: Create Caddyfile
  copy: content="{{caddy_config}}" dest=/etc/caddy/Caddyfile owner={{ caddy_user }}
  become: true
  notify: Restart Caddy

- name: Set default site on port 80
  template: src=403.html dest=/var/www/html/403.html mode=0644
  become: true

- name: Systemd service
  template: src=caddy.service dest=/etc/systemd/system/caddy.service mode=0755
  become: true
  notify: Reload systemd service file

- name: Check if the binary can bind to TCP port <1024
  shell: getcap /usr/local/bin/caddy | grep cap_net_bind_service
  failed_when: False
  changed_when: False
  become: true
  register: caddy_bind_cap

- name: Set capability on the binary file to be able to bind to TCP port <1024
  command: setcap cap_net_bind_service=+ep /usr/local/bin/caddy
  when: caddy_bind_cap.rc > 0
  become: true

- name: Start Caddy service
  service: name=caddy state=started enabled=yes
  become: true
