- name: Install nethog dependancies
  apt: pkg="{{item}}" state=present
  become: true
  with_items:
      - build-essential 
      - libncurses5-dev 
      - libpcap-dev
  when: ansible_distribution == "Ubuntu"

- name: Pull nethogs repo from github
  git: clone=yes repo=https://github.com/raboof/nethogs dest=/tmp/nethogs/ 
  register: diff

- name: Build and install nethogs
  become: true
  shell: "cd /tmp/nethogs && \ 
          make && \
          make install"
  when: diff.changed
