- name: Install Common Packages
  apt: pkg={{item}} state=present
  when: ansible_distribution == "Ubuntu"
  become: true
  with_items:
    - iptables-persistent

- name: Copy over firewall script
  template: src=firewall.sh.j2 dest=/usr/local/bin/firewall.sh mode=0755
  become: true  
      
- name: Run rules script
  shell: /usr/local/bin/firewall.sh
  become: true   
 
- name: Save rules to disk
  command: /usr/sbin/invoke-rc.d netfilter-persistent save
  become: true    
