- name: install epel
  yum: pkg={{ item }} state=present
  with_items:
     - epel-release
  become: true

- name: install nginx
  yum: pkg={{ item }} state=present
  with_items:
     - nginx
  become: true

- name: install custom nginx config
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf 
  become: true
  notify: restart nginx

- name: create /var/www folder 
  file: path=/var/www state=directory mode=755 owner=nginx group=nginx 
  become: true 

- name: open http Port  
  firewalld: service=http permanent=true immediate=yes state=enabled 

- name: restart nginx
  systemd:
    state: restarted
    daemon_reload: yes
    name: nginx
    enabled: true